# Fleiss Kappa for the CV Dataset Task

In [ ]:
%pip install statsmodels.stats.inter_rater

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement statsmodels.stats.inter_rater (from versions: none)
ERROR: No matching distribution found for statsmodels.stats.inter_rater

In [3]:
import pandas as pd

cv_mithlesh=pd.read_csv("Mithlesh_CV.csv")
cv_jenil=pd.read_csv("JENIL_CV.csv")
# cv_outsider=pd.read_csv("py.csv")

In [4]:
cv_jenil

,annotation_id,annotator,choice,created_at,id,image,lead_time,updated_at
0,12,1,No Trucks,2025-01-24T13:01:19.691513Z,31,/data/upload/2/49510674-img_705.jpg,33.018,2025-01-24T15:24:11.556155Z
1,13,1,No Trucks,2025-01-24T13:01:23.777567Z,32,/data/upload/2/e44ac6de-img_706.jpg,12.409,2025-01-24T15:24:18.131213Z
2,14,1,No Trucks,2025-01-24T13:01:27.357938Z,33,/data/upload/2/5617ac5d-img_707.jpg,3.464,2025-01-24T15:24:20.201558Z
3,15,1,Trucks,2025-01-24T13:01:30.719072Z,34,/data/upload/2/d8388828-img_708.jpg,6.233,2025-01-24T15:24:22.367729Z
4,16,1,Trucks,2025-01-24T13:01:37.359168Z,35,/data/upload/2/9cb0ee26-img_709.jpg,8.032,2025-01-24T15:24:24.729665Z
5,17,1,No Trucks,2025-01-24T13:01:40.986467Z,36,/data/upload/2/f0acc3af-img_710.jpg,4.491,2025-01-24T15:24:29.287414Z
6,18,1,No Trucks,2025-01-24T13:01:44.433887Z,37,/data/upload/2/9e74395a-img_711.jpg,4.117,2025-01-24T15:24:36.294319Z
7,19,1,Trucks,2025-01-24T13:01:58.174251Z,38,/data/upload/2/e373fe5d-img_712.jpg,15.009,2025-01-24T15:24:41.448383Z
8,20,1,No Trucks,2025-01-24T13:02:23.715729Z,39,/data/upload/2/80537bce-img_713.jpg,27.118,2025-01-24T15:24:50.282716Z
9,21,1,Trucks,2025-01-24T13:02:31.515241Z,40,/data/upload/2/20a6fb8a-img_714.jpg,8.738,2025-01-24T15:24:53.346607Z
10,22,1,Trucks,2025-01-24T13:02:34.490064Z,41,/data/upload/2/834272d5-img_715.jpg,3.699,2025-01-24T15:24:55.961857Z
11,23,1,No Trucks,2025-01-24T13:02:37.713123Z,42,/data/upload/2/3e81ad2f-img_716.jpg,3.690,2025-01-24T15:25:02.980882Z
12,24,1,Trucks,2025-01-24T13:02:40.546743Z,43,/data/upload/2/42767c46-img_717.jpg,3.608,2025-01-24T15:25:05.637976Z
13,25,1,No Trucks,2025-01-24T13:02:44.198694Z,44,/data/upload/2/5924198c-img_718.jpg,7.684,2025-01-24T15:25:12.047809Z
14,26,1,No Trucks,2025-01-24T13:02:47.728449Z,45,/data/upload/2/3cb161a5-img_719.jpg,3.870,2025-01-24T15:25:16.420316Z
15,27,1,No Trucks,2025-01-24T13:02:51.160774Z,46,/data/upload/2/31b8ebc3-img_700.jpg,3.157,2025-01-24T15:25:18.760444Z
16,28,1,No Trucks,2025-01-24T13:02:56.479336Z,47,/data/upload/2/152ab980-img_701.jpg,5.634,2025-01-24T15:25:20.926854Z
17,29,1,No Trucks,2025-01-24T13:03:00.662125Z,48,/data/upload/2/fb95f3e7-img_702.jpg,4.583,2025-01-24T15:25:23.424041Z
18,30,1,No Trucks,2025-01-24T13:03:04.215737Z,49,/data/upload/2/dd979da8-img_703.jpg,4.056,2025-01-24T15:25:26.239869Z
19,31,1,Trucks,2025-01-24T13:03:10.004560Z,50,/data/upload/2/e48c22e3-img_704.jpg,4.594,2025-01-24T15:25:29.667002Z

In [5]:
cv_mithlesh_annotation=cv_mithlesh.iloc[:,2]
cv_mithlesh_annotation

0     No Trucks
1     No Trucks
2     No Trucks
3     No Trucks
4        Trucks
5     No Trucks
6        Trucks
7     No Trucks
8        Trucks
9        Trucks
10    No Trucks
11    No Trucks
12       Trucks
13    No Trucks
14    No Trucks
15    No Trucks
16    No Trucks
17       Trucks
18       Trucks
19    No Trucks
Name: choice, dtype: object

In [6]:
nlp_annotator1_labels = nlp_mithlesh['label'].apply(lambda x: [entry['labels'][0] for entry in eval(x)]).tolist()

NameError: name 'nlp_mithlesh' is not defined

In [20]:
nlp_flatten_annotator1 = [label for sublist in nlp_annotator1_labels for label in sublist]

In [21]:
import pandas as pd
from sklearn.metrics import cohen_kappa_score

In [ ]:
kappa_score = cohen_kappa_score(nlp_flatten_annotator1, nlp_flatten_annotator2)  # Replace the second list with the real annotator 2
print(f"Cohen's Kappa: {kappa_score}")

In [29]:
import pandas as pd
from statsmodels.stats.inter_rater import fleiss_kappa



# Extract the two columns
choice_column = cv_mithlesh["choice"]
second_column = cv_jenil["choice"]

# Organize data into a rating matrix
# Assuming categories are integers or labels, create the rating matrix
categories = sorted(set(choice_column) | set(second_column))  # All unique categories
rating_matrix = []

for i in range(len(choice_column)):
    row = [0] * len(categories)
    row[categories.index(choice_column[i])] += 1
    row[categories.index(second_column[i])] += 1
    rating_matrix.append(row)

# Convert to DataFrame for clarity (optional)
rating_df = pd.DataFrame(rating_matrix, columns=categories)

# Calculate Fleiss' Kappa
kappa = fleiss_kappa(rating_df.values, method='fleiss')
print("Fleiss' Kappa:", kappa)

Fleiss' Kappa: 0.12087912087912075

In [30]:
rating_df

    No Trucks  Trucks
0           2       0
1           2       0
2           2       0
3           1       1
4           0       2
5           2       0
6           1       1
7           1       1
8           1       1
9           0       2
10          1       1
11          2       0
12          0       2
13          2       0
14          2       0
15          2       0
16          2       0
17          1       1
18          1       1
19          1       1

In [3]:
import pandas as pd
from statsmodels.stats.inter_rater import fleiss_kappa

# Assuming `cv_mithlesh`, `cv_jenil`, and `cv_third` DataFrames have a "choice" column
# Extract the three choice columns
choice_column_1 = cv_mithlesh["choice"]
choice_column_2 = cv_jenil["choice"]
choice_column_3 = cv_outsider["choice"]

# Organize data into a rating matrix
# Assuming categories are integers or labels, create the rating matrix
categories = sorted(set(choice_column_1) | set(choice_column_2) | set(choice_column_3))  # All unique categories
rating_matrix = []

for i in range(len(choice_column_1)):
    row = [0] * len(categories)
    row[categories.index(choice_column_1[i])] += 1
    row[categories.index(choice_column_2[i])] += 1
    row[categories.index(choice_column_3[i])] += 1
    rating_matrix.append(row)

# Convert to DataFrame for clarity (optional)
rating_df = pd.DataFrame(rating_matrix, columns=categories)

# Calculate Fleiss' Kappa
kappa = fleiss_kappa(rating_df.values, method='fleiss')
print("Fleiss' Kappa:", kappa)

Fleiss' Kappa: 0.35406698564593314